version: '3'
name: geneve-test

services:
  es:
    image: ${TEST_ELASTICSEARCH_IMAGE:-docker.elastic.co/elasticsearch/elasticsearch:${TEST_STACK_VERSION:-8.12.0}}
    environment:
      - node.name=es
      - cluster.name=geneve-test
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 127.0.0.1:29650:9200
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "[ -e kibana_system_ready ] || curl -s -X POST -H 'Content-Type: application/json' -u elastic:changeme http://es:9200/_security/user/kibana_system/_password -d '{\"password\":\"changeme\"}' | grep -q '^{}' && touch kibana_system_ready"]
      interval: 5s
      retries: 15
      timeout: 10s
  kbn:
    depends_on: [es]
    image: ${TEST_KIBANA_IMAGE:-docker.elastic.co/kibana/kibana:${TEST_STACK_VERSION:-8.12.0}}
    environment:
      SERVER_NAME: kbn
      ELASTICSEARCH_HOSTS: ${TEST_ELASTICSEARCH_PROXY:-http://es:9200}
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: changeme
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: 0123456789abcdef0123456789ABCDEF
    ports:
      - 127.0.0.1:65290:5601
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "curl -s -X GET -u elastic:changeme http://kbn:5601/api/task_manager/_health | grep -q '\"status\":\"OK\"'"]
      interval: 5s
      retries: 15
      timeout: 10s

networks:
  net:
    driver: bridge
