name: Main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

env:
  TEST_VERBOSITY: 2

jobs:
  license-check:
    name: License check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: License check
        run: make license-check

  unit-tests-matrix:
    name: Unit tests matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build matrix
        id: build-matrix
        run: echo "::set-output name=matrix::$(make -s unit_tests_matrix)"

  unit-tests:
    name: Unit tests (${{ matrix.os }}/py-${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    needs: unit-tests-matrix

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.unit-tests-matrix.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make prereq-py

      - name: Lint code
        run: make lint

      - name: Run unit tests
        env:
          TEST_SCHEMA_URI: "./etc/ecs-8.1.0.tar.gz"
          TEST_DETECTION_RULES_URI: "./etc/detection-rules-8.1.0.tar.gz"
        run: make tests

  online-tests:
    name: Online tests (${{ matrix.stack-version }})
    runs-on: "ubuntu-latest"
    needs:
      - unit-tests
      - cli

    strategy:
      fail-fast: false
      matrix:
        stack-version:
          - 8.4.0
          - 8.3.0
          - 8.2.0
          - 8.1.0
        schema-uri: ["./etc/ecs-8.1.0.tar.gz"]
        detection-rules-uri: ["./etc/detection-rules-8.1.0.tar.gz"]
        signals_queries: [1]
        signals_rules: [1]

        include:
          - stack-version: "7.17.0"
            schema-uri: "./etc/ecs-8.1.0.tar.gz"
            detection-rules-uri: "./etc/detection-rules-8.1.0.tar.gz"
            signals_queries: 1
            signals_rules: 0  # https://github.com/elastic/geneve/issues/28

          - stack-version: "7.16.0"
            schema-uri: "./etc/ecs-8.1.0.tar.gz"
            detection-rules-uri: "./etc/detection-rules-8.1.0.tar.gz"
            signals_queries: 1
            signals_rules: 0  # https://github.com/elastic/geneve/issues/28

          - stack-version: "7.15.0"
            schema-uri: "./etc/ecs-8.1.0.tar.gz"
            detection-rules-uri: "./etc/detection-rules-8.1.0.tar.gz"
            signals_queries: 1
            signals_rules: 1

    env:
      TEST_ELASTICSEARCH_URL: "http://elastic:changeme@localhost:29650"
      TEST_KIBANA_URL: "http://elastic:changeme@localhost:65290"
      TEST_GENEVE_LOG: "gnv.log"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.19"

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          make prereq-go
          make prereq-py

      - name: Build CLI
        run: make cli-build

      - name: Start Geneve server
        run: |
          ./gnv serve -l 0.0.0.0:9280 -r $TEST_ELASTICSEARCH_URL --log $TEST_GENEVE_LOG 2>>gnv.log &
          curl -s --retry 3 --retry-connrefused http://localhost:9256/api/status
          curl -s -XPOST -H "Content-Type: application/yaml" http://localhost:9256/api/grasp/ignore --data-binary '@tests/grasp-ignore.yaml'

      - name: Setup cache
        id: elastic-stack-cache
        uses: actions/cache@v2
        with:
          key: elastic-stack-cache-${{ matrix.stack-version }}
          path: ~/elastic-stack-cache

      - name: Reuse Elastic Stack ${{ matrix.stack-version }} Docker images
        if: steps.elastic-stack-cache.outputs.cache-hit == 'true'
        run: |
          docker load -i ~/elastic-stack-cache/elasticsearch-${{ matrix.stack-version }}.tar
          docker load -i ~/elastic-stack-cache/kibana-${{ matrix.stack-version }}.tar

      - name: Pull Elastic Stack ${{ matrix.stack-version }} Docker images
        if: steps.elastic-stack-cache.outputs.cache-hit != 'true'
        env:
          TEST_STACK_VERSION: ${{ matrix.stack-version }}
        run: |
          mkdir ~/elastic-stack-cache
          docker compose pull -q
          docker save -o ~/elastic-stack-cache/elasticsearch-${{ matrix.stack-version }}.tar \
            docker.elastic.co/elasticsearch/elasticsearch:${{ matrix.stack-version }}
          docker save -o ~/elastic-stack-cache/kibana-${{ matrix.stack-version }}.tar \
            docker.elastic.co/kibana/kibana:${{ matrix.stack-version }}

      - name: Start Elastic Stack ${{ matrix.stack-version }}
        env:
          TEST_STACK_VERSION: ${{ matrix.stack-version }}
          TEST_ELASTICSEARCH_PROXY: "http://host.docker.internal:9280"
        run: make up

      - name: Run online tests
        env:
          TEST_SCHEMA_URI: ${{ matrix.schema-uri }}
          TEST_DETECTION_RULES_URI: ${{ matrix.detection-rules-uri }}
          TEST_SIGNALS_QUERIES: ${{ matrix.signals_queries }}
          TEST_SIGNALS_RULES: ${{ matrix.signals_rules }}
          TEST_ELASTICSEARCH_URL: "http://localhost:9280"
        run: make online-tests

      - name: Stop Elastic Stack ${{ matrix.stack-version }}
        run: make down

      - name: Stop Geneve server
        if: always()
        run: |
          curl -s "http://localhost:9256/api/grasp"
          curl -s "http://localhost:9256/api/grasp/indices?percent=100"
          curl -s "http://localhost:9256/api/grasp/calls?percent=100"
          curl -s "http://localhost:9256/api/grasp/searches?percent=100"
          killall gnv
          if grep "WARNING: DATA RACE" $TEST_GENEVE_LOG; then awk '/WARNING: DATA RACE/{found=1} found' $TEST_GENEVE_LOG; false; fi

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: geneve-log-${{ matrix.stack-version }}
          path: gnv.log

  cli:
    name: CLI (${{ matrix.os }}/go-${{ matrix.go-version }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.18", "1.19"]
        os: ["ubuntu-latest", "macos-latest"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: make prereq-go

      - name: Build
        run: make cli-build

      - name: Lint
        run: make cli-lint

      - name: Test
        run: make cli-test

      - name: Benchmark
        run: make cli-bench

  package-build:
    name: Package build (${{ matrix.os }}/py-${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: ["ubuntu-latest", "macos-latest"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make prereq-py

      - name: Build package
        run: make package

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-package-${{ matrix.python-version }}-${{ matrix.os }}
          path: dist/geneve-*.whl

  package-tests:
    name: Package tests (${{ matrix.os }}/py-${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    needs: package-build

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: ["ubuntu-latest", "macos-latest"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: code

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: python-package-${{ matrix.python-version }}-${{ matrix.os }}
          path: dist

      - name: Install package
        run: make -f code/Makefile pkg-install

      - name: Test package
        run: make -f code/Makefile pkg-tests

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - license-check
      - unit-tests
      - online-tests
      - package-tests
      - cli
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: python-package-3.8-ubuntu-latest
          path: dist

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        if: github.repository != 'elastic/geneve'
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          print_hash: true
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        if: github.repository == 'elastic/geneve'
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          print_hash: true
